// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktcfjwjhulvgwnxuddfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0Y2Zqd2podWx2Z3dueHVkZGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyMzE0NDEsImV4cCI6MjA5OTgwNzQ0MX0.QcQPxCQzcnD7ED5yAeBMX2ugA1jh1ijVtUUg8z-PgCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});